export default [
  {
    data: '{}',
    ref: {},
    defaultValue: undefined,
    displayValue: '{}',
  },
  {
    data: '[]',
    ref: [],
    defaultValue: undefined,
    displayValue: '[]',
  },
  {
    data: '{"a":1}',
    ref: { a: 1 },
    defaultValue: undefined,
    displayValue: '{ a: 1 }',
  },
  {
    data: '{"a":1,"b":2,"c":3}',
    ref: { a: 1, b: 2, c: 3 },
    defaultValue: undefined,
    displayValue: '{ a: 1, b: 2, c: 3 }',
  },
  {
    data: '{\n  "a": 1,\n  "b": 2,\n  "c": 3\n}',
    ref: { a: 1, b: 2, c: 3 },
    defaultValue: 2,
    displayValue: '{ a: 1, b: 2, c: 3 }',
  },
  {
    data: '[1,2,3]',
    ref: [1, 2, 3],
    defaultValue: undefined,
    displayValue: '[1, 2, 3]',
  },
  {
    data: '["a","b","c"]',
    ref: ['a', 'b', 'c'],
    defaultValue: undefined,
    displayValue: "['a', 'b', 'c']",
  },
  {
    data: '[\n  "a",\n  "b",\n  "c"\n]',
    ref: ['a', 'b', 'c'],
    defaultValue: 2,
    displayValue: "['a', 'b', 'c']",
  },
  {
    data: '{"a":"ABCdef","b":123,"c":"123","d":"","e":null,"f":true,"g":false,"h":[1,2,3],"i":["1","2","3"],"j":["a","b","c"],"k":{"a":1,"b":2,"c":3}}',
    ref: {
      a: 'ABCdef',
      b: 123,
      c: '123',
      d: '',
      e: null,
      f: true,
      g: false,
      h: [1, 2, 3],
      i: ['1', '2', '3'],
      j: ['a', 'b', 'c'],
      k: { a: 1, b: 2, c: 3 },
    },
    defaultValue: undefined,
    displayValue:
      "{ a: 'ABCdef', b: 123, c: '123', d: '', e: null, f: true, g: false, h: [1, 2, 3], i: ['1', '2', '3'], j: ['a', 'b', 'c'], k: { a: 1, b: 2, c: 3 }}",
  },
  {
    data: 123,
    ref: undefined,
    defaultValue: undefined,
    displayValue: '123',
  },
  {
    data: 'abc',
    ref: undefined,
    defaultValue: undefined,
    displayValue: 'abc',
  },
  {
    data: true,
    ref: undefined,
    defaultValue: undefined,
    displayValue: 'true',
  },
  {
    data: false,
    ref: undefined,
    defaultValue: undefined,
    displayValue: 'false',
  },
  {
    data: null,
    ref: { a: 1 },
    defaultValue: { a: 1 },
    displayValue: 'null with default { a: 1 }',
  },
];
